#if defined __cplusplus
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream> 
#include <map>
#include <QApplication>
#include <QByteArray>
#include <QCheckBox>
#include <QCloseEvent>
#include <QComboBox>
#include <QCoreApplication>
#include <QCryptographicHash>
#include <QDateTime>
#include <QDesktopServices>
#include <QDialog>
#include <QDir>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFileSystemWatcher>
#include <QGLWidget>
#include <QGraphicsPixmapItem>
#include <QGraphicsScene>
#include <QGraphicsView>
#include <QHBoxLayout>
#include <QImage>
#include <QInputDialog>
#include <QLabel>
#include <QList>
#include <QListWidget>
#include <QMap>
#include <QMessageBox>
#include <QMetaType>
#include <QMutex>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QObject>
#include <QPainter>
#include <QPixmap>
#include <QPlainTextEdit>
#include <QProcess>
#include <QProcessEnvironment>
#include <QRegExp>
#include <QRegExpValidator>
#include <QRgb>
#include <QSettings>
#include <QSplitter>
#include <QString>
#include <QStringList>
#include <QtCore/qglobal.h>
#include <QtCore/QVariant>
#include <QtDebug>
#include <QTemporaryFile>
#include <QTextStream>
#include <QtGui>
#include <QAction>
#include <QApplication>
#include <QButtonGroup>
#include <QCheckBox>
#include <QComboBox>
#include <QDialog>
#include <QDoubleSpinBox>
#include <QFrame>
#include <QGridLayout>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QLabel>
#include <QLineEdit>
#include <QPlainTextEdit>
#include <QProgressBar>
#include <QPushButton>
#include <QRadioButton>
#include <QSlider>
#include <QSpacerItem>
#include <QSpinBox>
#include <QTabWidget>
#include <QVBoxLayout>
#include <QWidget>
#include <QThread>
#include <QThread>
#include <QTime>
#include <QTimer>
#include <QtNetwork/QNetworkReply>
#include <QtOpenGL>
#include <QVBoxLayout>
#include <QVector>
#include <QWebView>
#include <QWidget>
#include <sstream>
#include <vector> 
#endif

