.TH ltr_fgfs 1 "17 March 2011"
.IX ltr_fgfs
.SH NAME
ltr_fgfs - send tracker data to FlightGear flight simulator.
.SH SYNOPSYS
.B ltr_fgfs
.RI [-?V]
.RI [-h\ HOST]
.RI [-p\ PORT]
.RI [-f\ NAME]
.RI [-t\ SECONDS]
.RI [--fg-host=HOST]
.RI [--fg-port=PORT]
.RI [--ltr-profile=NAME]
.RI [--ltr-timeout=SECONDS]
.RI [--help]
.RI [--usage]
.RI [--version]
.SH DESCRIPTION
ltr_fgfs is a client executable that allows to send tracker data to
FlightGear flight simulator using UDP.
.SH OPTIONS
.TP
.B -h <HOST>, --fg-host=<HOST>
Hostname or IP address of FlightGear host (default: localhost). 
.TP
.B -p <PORT>, --fg-port=<PORT>
FlightGear port where it listens to incoming tracker data (default: 6543).
.TP
.B -f <NAME>, --ltr-profile=<NAME>
Linux-track profile name (default: Default).
.TP
.B -t <SECONDS>, --ltr-timeout=<SECONDS>
Linux-track initialization timeout in seconds (default: 10).
.TP
.B -?, --help
Give help list.
.TP
.B --usage
Give a short usage message.
.TP
.B -V, --version
Print program version.

