#!/bin/bash
#
#Assumes you have libusb-1.0.8.tar.bz2 and XPlane SDK in the parent directory.
#
cd ..
BASE=`pwd`
PREFIX=${BASE}/ltr
LIB_DIR=ltr_gui.app/Contents/Frameworks
BIN_DIR=ltr_gui.app/Contents/MacOS
HELPER_DIR=ltr_gui.app/Contents/helper
WII_SRVR_DIR=
export MACOSX_DEPLOYMENT_TARGET=10.4
##Build libusb-1.0
if [ -f ${PREFIX}/lib/libusb-1.0.dylib ]; then
  echo 'Libusb-1.0 already exists!'
else
  export CFLAGS=" -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4 "
  tar xfj libusb-1.0.8.tar.bz2
  pushd libusb-1.0.8
  ./configure --prefix=${PREFIX} --disable-dependency-tracking >/dev/null
  make >/dev/null
  make install >/dev/null
  unset CFLAGS
  popd
fi

#Build linuxtrack
pushd michal
autoreconf -if
export CFLAGS="-I${PREFIX}/include "
export LDFLAGS="-L${PREFIX}/lib "
./configure --prefix=${PREFIX} >/dev/null
make >/dev/null
make install >/dev/null

#Build gui - should not be needed anymore
pushd src/qt_gui
qmake -spec macx-g++
rm -rf ltr_gui.app
make install >/dev/null

#Prepare the image
mkdir -p ${LIB_DIR}
mkdir -p ${HELPER_DIR}

cp -R ${PREFIX}/lib/libltusb1.0.dylib ${LIB_DIR}
cp -R ${PREFIX}/lib/libtir.0.dylib ${LIB_DIR}
cp -R ${PREFIX}/lib/libmacwc.0.dylib ${LIB_DIR}
cp -R ${PREFIX}/lib/libmacwii.0.dylib ${LIB_DIR}
cp -R ${PREFIX}/lib/libusb-1.0.0.dylib ${LIB_DIR}/libusb-1.0.dylib
cp -R ${PREFIX}/lib/xlinuxtrack.0.so ${LIB_DIR}/xlinuxtrack.0.dylib
cp -R ${PREFIX}/bin/qt_cam ${HELPER_DIR}
cp -R ${PREFIX}/bin/sg_cam ${HELPER_DIR}

install_name_tool -id @loader_path/libusb-1.0.0.dylib ${LIB_DIR}/libusb-1.0.dylib
install_name_tool -id @loader_path/libltusb1.0.dylib ${LIB_DIR}/libltusb1.0.dylib
install_name_tool -id @executable_path/../Frameworks/libtir.0.dylib ${LIB_DIR}/libtir.0.dylib
install_name_tool -id @executable_path/../Frameworks/libmacwc.0.dylib ${LIB_DIR}/libmacwc.0.dylib
install_name_tool -id @executable_path/../Frameworks/libmacwii.0.dylib ${LIB_DIR}/libmacwii.0.dylib
install_name_tool -id @executable_path/../Frameworks/xlinuxtrack.0.dylib ${LIB_DIR}/xlinuxtrack.0.dylib

install_name_tool -change "${PREFIX}/lib/libusb-1.0.0.dylib" \
  @loader_path/libusb-1.0.dylib ${LIB_DIR}/libltusb1.0.dylib
install_name_tool -change "${PREFIX}/lib/liblinuxtrack.0.dylib" \
  @loader_path/liblinuxtrack.0.dylib ${LIB_DIR}/libltusb1.0.dylib
install_name_tool -change "${PREFIX}/lib/liblinuxtrack.0.dylib"  \
  @loader_path/liblinuxtrack.0.dylib "${LIB_DIR}/libtir.0.dylib"
install_name_tool -change "${PREFIX}/lib/liblinuxtrack.0.dylib"  \
  @loader_path/liblinuxtrack.0.dylib "${LIB_DIR}/libmacwc.0.dylib"
install_name_tool -change "${PREFIX}/lib/liblinuxtrack.0.dylib"  \
  @loader_path/liblinuxtrack.0.dylib "${LIB_DIR}/libmacwii.0.dylib"

install_name_tool -change "${PREFIX}/lib/liblinuxtrack.0.dylib" \
  @executable_path/../Frameworks/liblinuxtrack.0.dylib ${HELPER_DIR}/qt_cam
install_name_tool -change "${PREFIX}/lib/liblinuxtrack.0.dylib" \
  @executable_path/../Frameworks/liblinuxtrack.0.dylib ${HELPER_DIR}/sg_cam

rm -f ltr_gui.dmg

#Create archive image
macdeployqt ltr_gui.app -no-strip
popd

rm -rf dist
mkdir dist
pushd dist
  mkdir -p WiiServer.app/Contents/MacOS
  mkdir -p WiiServer.app/Contents/Frameworks/
  mkdir -p WiiServer.app/Contents/Resources/
  cp -r ../src/mac/English.lproj WiiServer.app/Contents/Resources
  cp ../src/mac/Info.plist WiiServer.app/Contents
  cp ../src/mac/PkgInfo WiiServer.app/Contents
  cp -R ${PREFIX}/bin/WiiServer WiiServer.app/Contents/MacOS
  cp -R ${PREFIX}/lib/liblinuxtrack.0.dylib WiiServer.app/Contents/Frameworks/
  install_name_tool -id @executable_path/../Frameworks/liblinuxtrack.0.dylib \
    WiiServer.app/Contents/Frameworks/liblinuxtrack.0.dylib
  install_name_tool -change ${PREFIX}/lib/liblinuxtrack.0.dylib \
    @executable_path/../Frameworks/liblinuxtrack.0.dylib WiiServer.app/Contents/MacOS/WiiServer

  mv ../src/qt_gui/ltr_gui.app .
  if [ -f "${BASE}/bulk_config_data.tar.gz" ]; then
    pushd ltr_gui.app/Contents/Resources/linuxtrack
      tar xfz ${BASE}/bulk_config_data.tar.gz
    popd 
  fi
popd
rm -f linuxtrack.dmg
hdiutil create linuxtrack.dmg -srcfolder dist -format UDZO -volname linuxtrack

popd
#
