.TH ltr_extractor 1 "23 July 2014"
.IX ltr_extractor
.SH NAME
ltr_extractor - extracts TrackIR/SmartNav firmware files and other necessary informations needed by Linuxtrack
.SH SYNOPSYS
.B ltr_extractor --extract | --update | --create [--spec file] file1 [file2 ... ]
.SH DESCRIPTION
ltr_extractor allows user to extract files necessary for Linuxtrack to utilize TrackIR/SmartNav devices.
These files are extracted from NaturalPoint's TrackIR software; the software itself can be installed using 
Wine (however it will not run), or can be copied from a Windows machine.
.SH COMMANDS
.TP
.B --extract
Extracts firmware files, etc. from the files specified as the rest of arguments.
.TP
.B --create
For developer's usage - create signatures of files provided.
.TP
.B --update
When updated game identifiers are downloaded, this command decrypts the informations.
.SH OPTIONS
.TP
.B --spec
Specify alternative spec file; when used with --extract, extraction uses this file instead of the default one.
When used with --create, the data are written to the specified file.
.B fileX
Name of file/files to be processed.

.SH Example of the extraction
You can download the NP software from the company website and install it the following way
to a temporary prefix:
 
.B mkdir /tmp/np
.br
.B WINEPREFIX=/tmp/np wine ~/Downloads/TrackIR_5.2.2.Final.exe

Just follow the instructions and install the software. When the software is installed, 
you can proceed to extraction:

.B ltr_extractor --extract \\\\
.br
.B /tmp/np/drive_c/Program\\\\ Files\\\\ \\\(x86\\\\)/NaturalPoint/TrackIR5/*

If all goes well, the necessary files are extracted.

.SH Example of the spec creation
Command 

.B ltr_extractor --create --spec ./spec.txt poem1.txt poem2.txt tir4.fw

Prints signatures of files passed in; please note, that the firmware files have to be
ungzipped first. Results are written to the file spec.txt in the current directory.

.SH Example of the game files update
When using Linuxtrack in Wine, the game IDs and sometimes a communication keys are needed.
To download the update, use the following comand:

.B ltr_extractor --update


