.TH wii_server 1 "22 January 2011"
.IX wii_server
.SH NAME
wii_server - facilitating connection to the wiimote
.SH SYNOPSYS
.B wii_server
.SH DESCRIPTION
wii_server is a helper executable, allowing you to pair wiimote only once, 
maintaining connection even when linuxtrack enabled software is not running
at the moment.
.SH USAGE
Run wii_server, press Connect button and then press "1" and "2" on your 
wiimote simultaneously to put wiimote into discoverable mode. After a short
while the wii_server should indicate success of the connection attempt.
Wiimote indicates successfull connection by blinking one of LEDs about once
every five seconds.

