.TH ltr_server1 1 "11 May 2014"
.IX ltr_server1
.SH NAME
ltr_server1 - setup head tracking parameters
.SH SYNOPSYS
.B ltr_server1
.RI filename
.RI [ section_name ]
.SH DESCRIPTION
ltr_server1 is a helper executable, allowing to decouple application
from the actual tracker. User is not supposed to run this command directly.
.SH OPTIONS
.TP
.B filename
Then name of file used to communicate between tracker and the application.
.TP
.B section_name
Name of the linuxtrack profile to be used. If not specified, default profile 
is used.

