#if defined __cplusplus
#include <cmath>
#include <cstdio>
#include <iostream>
#include <map>
#include <QAbstractEventDispatcher>
#include <QApplication>
#include <QBoxLayout>
#include <QCloseEvent>
#include <QCursor>
#include <QDesktopWidget>
#include <QDialog>
#include <QKeySequence>
#include <QLocale>
#include <QMessageBox>
#include <QMutex>
#include <QObject>
#include <QPainter>
#include <QPixmap>
#include <QSettings>
#include <QtCore/qglobal.h>
#include <QtCore/QVariant>
#include <QAction>
#include <QApplication>
#include <QButtonGroup>
#include <QCheckBox>
#include <QComboBox>
#include <QFrame>
#include <QGridLayout>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QLabel>
#include <QPushButton>
#include <QRadioButton>
#include <QSlider>
#include <QSpacerItem>
#include <QSpinBox>
#include <QTabWidget>
#include <QVBoxLayout>
#include <QWidget>
#include <QThread>
#include <QTime>
#include <QTimer>
#include <QVBoxLayout>
#include <QWidget>
#include <QX11Info>
#endif

