.TH ltr_server 1 "22 January 2011"
.IX ltr_server
.SH NAME
ltr_server - setup head tracking parameters
.SH SYNOPSYS
.B ltr_server
.RI filename
.RI [ section_name ]
.SH DESCRIPTION
ltr_server is a helper executable, allowing to decouple application
from the actual tracker. User is not supposed to run this command directly.
.SH OPTIONS
.TP
.B filename
Then name of file used to communicate between tracker and the application.
.TP
.B section_name
Name of the linuxtrack profile to be used. If not specified, default profile 
is used.

