#if defined __cplusplus
#include <cmath>
#include <cstdio>
#include <iostream>
#include <map>
#include <QAbstractEventDispatcher>
#include <QApplication>
#include <QBoxLayout>
#include <QCloseEvent>
#include <QCursor>
#include <QDesktopWidget>
#include <QDialog>
#include <QKeySequence>
#include <QLocale>
#include <QMessageBox>
#include <QMutex>
#include <QObject>
#include <QPainter>
#include <QPixmap>
#include <QSettings>
#include <QtCore/qglobal.h>
#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QFrame>
#include <QtGui/QGridLayout>
#include <QtGui/QGroupBox>
#include <QtGui/QHBoxLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QSlider>
#include <QtGui/QSpacerItem>
#include <QtGui/QSpinBox>
#include <QtGui/QTabWidget>
#include <QtGui/QVBoxLayout>
#include <QtGui/QWidget>
#include <QThread>
#include <QTime>
#include <QTimer>
#include <QVBoxLayout>
#include <QWidget>
#include <QX11Info>
#endif

